### ISSUE TITLE
SSL和CDN支持问题

### ISSUE THREAD

**Issue by baby9** [walkor/BrowserQuest-PHP#12]
我想要在网站上套cloudflare的CDN，其CDN支持443，2083，8443等端口的SSL流量，我需要修改什么配置才能实现。
另 #5  该网站配置SSL相关已无

**Comment by walkor** [comment]
ssl 配置手册
https://www.workerman.net/doc/workerman/faq/secure-websocket-server.html

官方不熟悉cloudflare CDN，如何配置cloudflare的CDN并不清楚

**Comment by baby9** [comment]
> ssl 配置手册 https://www.workerman.net/doc/workerman/faq/secure-websocket-server.html
> 
> 官方不熟悉cloudflare CDN，如何配置cloudflare的CDN并不清楚

Thank you for reply
