### ISSUE TITLE
websocket問題

### ISSUE THREAD

**Issue by taiwan-king** [walkor/BrowserQuest-PHP#13]
我已經依照你的說明改成我的域名並重啟Server
更改配置 Web/config/config_local.json 中的host为当前服务器ip地址或者域名

但是我看連線還是一直連你的demos.workerman.net:8000
是哪裡還需要做修正嗎?

另外我如果將config_build.json也改成我的域名
我看連線就會正常連我的網域,
但是websocket無法正常建立起來
![1681305341142](https://user-images.githubusercontent.com/24381898/231469551-9e4c75df-b2a5-4f25-9950-176f4989e3ae.jpg)

是哪邊還需要修正嗎?

**Comment by BrailleCortex** [comment]
How did you resolve this? I am having the same issue

**Comment by BrailleCortex** [comment]
I got it. Firefox had old data in cache, I deleted the site data for localhost and the issue was resolved

**Comment by taiwan-king** [comment]
> I got it. Firefox had old data in cache, I deleted the site data for localhost and the issue was resolved

https://hub.docker.com/r/crazyandy316945/browserquest

You can use it directly, I’ve already packaged it into an image. If you want to set it up under your own domain, then you’ll need to connect to the container for additional configuration.
