### ISSUE TITLE
Unable to run the server code in Windows envirnoment

### ISSUE THREAD

**Issue by nykevinwong** [walkor/BrowserQuest-PHP#3]
Hi walkor, 
I am unable to run the server in Windows environment. see below error messages.
What dependency I need to install to make it working in Windows environment?
by the way, I am a C#/.NET Web Developer and  I have no experience of using php.

Thanks,
Kevin

ERROR MESSAGES:
C:\projects\BrowserQuest-PHP>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

C:\projects\BrowserQuest-PHP>php start.php start
PHP Fatal error:  Uncaught Error: Call to undefined function Workerman\Lib\pcntl
_signal() in C:\projects\BrowserQuest-PHP\vendor\workerman\workerman\Lib\Timer.p
hp:57
Stack trace:
#0 C:\projects\BrowserQuest-PHP\vendor\workerman\workerman\Worker.php(489): Work
erman\Lib\Timer::init()
#1 C:\projects\BrowserQuest-PHP\vendor\workerman\workerman\Worker.php(424): Work
erman\Worker::init()
#2 C:\projects\BrowserQuest-PHP\start.php(25): Workerman\Worker::runAll()
#3 {main}
  thrown in C:\projects\BrowserQuest-PHP\vendor\workerman\workerman\Lib\Timer.ph
p on line 57

Fatal error: Uncaught Error: Call to undefined function Workerman\Lib\pcntl_sign
al() in C:\projects\BrowserQuest-PHP\vendor\workerman\workerman\Lib\Timer.php:57

Stack trace:
#0 C:\projects\BrowserQuest-PHP\vendor\workerman\workerman\Worker.php(489): Work
erman\Lib\Timer::init()
#1 C:\projects\BrowserQuest-PHP\vendor\workerman\workerman\Worker.php(424): Work
erman\Worker::init()
#2 C:\projects\BrowserQuest-PHP\start.php(25): Workerman\Worker::runAll()
#3 {main}
  thrown in C:\projects\BrowserQuest-PHP\vendor\workerman\workerman\Lib\Timer.ph
p on line 57

C:\projects\BrowserQuest-PHP>php start.php start -d
PHP Fatal error:  Uncaught Error: Call to undefined function Workerman\Lib\pcntl
_signal() in C:\projects\BrowserQuest-PHP\vendor\workerman\workerman\Lib\Timer.p
hp:57
Stack trace:
#0 C:\projects\BrowserQuest-PHP\vendor\workerman\workerman\Worker.php(489): Work
erman\Lib\Timer::init()
#1 C:\projects\BrowserQuest-PHP\vendor\workerman\workerman\Worker.php(424): Work
erman\Worker::init()
#2 C:\projects\BrowserQuest-PHP\start.php(25): Workerman\Worker::runAll()
#3 {main}
  thrown in C:\projects\BrowserQuest-PHP\vendor\workerman\workerman\Lib\Timer.ph
p on line 57

**Comment by walkor** [comment]
BrowserQuest-PHP not support windows.
