### ISSUE TITLE
服务器连接问题

### ISSUE THREAD

**Issue by OhMyAgnes** [walkor/BrowserQuest-PHP#4]
Server端正常启动 监听8000端口：
Workerman[start.php] start in DEBUG mode
----------------------- WORKERMAN -----------------------------
Workerman version:3.4.3          PHP version:7.0.6
------------------------ WORKERS -------------------------------
user          worker              listen                    processes status
root          BrowserQuestWorker  websocket://0.0.0.0:8000   1         [OK] 
\----------------------------------------------------------------
Press Ctrl-C to quit. Start success.
world1 created capacity: 1000 players 
然后把web端放到nginx的vhost目录下，配置文件config_local.json内容为
{
    "host": "x.x.x.x",    //x.x.x.x 为我的服务器IP
    "port": 8000,
    "dispatcher": false
}

访问网址，输入用户名之后就一直卡在Connecting to server...这个界面.
防火墙已关，请问是什么原因呢？

**Comment by walkor** [comment]
浏览器f12 看下报错

**Comment by OhMyAgnes** [comment]
VM44:35 WebSocket connection to 'ws://127.0.0.1:8000/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by walkor** [comment]
明显连错ip了

**Comment by OhMyAgnes** [comment]
奇怪了，WebSocket为什么要去连localhost 是我没设置对吗

**Comment by walkor** [comment]
代码里搜下 127关键字吧

**Comment by OhMyAgnes** [comment]
好的...
再请教下，有个问题一直没有明白。比如我访问这个网站的时候，web文件夹里面的.js代码是打开浏览器的电脑上执行的还是在服务器上？

**Comment by walkor** [comment]
js都是在浏览器上执行的
