### ISSUE TITLE
关于HTTPS支持问题

### ISSUE THREAD

**Issue by OhMyAgnes** [walkor/BrowserQuest-PHP#5]
请问服务端支持https吗？
支持的话是不是只需要改用WSS就行了？

**Comment by walkor** [comment]
需要参考php手册设置wss
http://doc.workerman.net/315297

修改start_worker.php

**Comment by OhMyAgnes** [comment]
多谢！
按照你给的链接，用Nginx作为SSL代理配置好了wss

**Comment by walkor** [comment]
不客气
