### ISSUE TITLE
deploying a production build question

### ISSUE THREAD

**Issue by quest0x** [walkor/BrowserQuest-PHP#9]
Hey! 
Im wondering what platform you used to launch the production build and if you needed to use anything to build it. 
im using Digital Ocean and it build everything and deploys to what looks normal but gives a failed build.
Appreciate your insight!
![deploy](https://user-images.githubusercontent.com/100332893/155649187-cb5b975b-60df-4376-aac5-f8d3d7fc791e.PNG)

**Comment by walkor** [comment]
I am using Alibaba cloud elastic server.
Run command `php start.php start -d`  for Linux.
Run command `php start_web.php start_worker.php ` for windows.

**Comment by quest0x** [comment]
ok i will give alibaba a try. when using php start.php start -d i get:
![error](https://user-images.githubusercontent.com/100332893/155852289-8a061ea3-5456-4067-b8c3-0e22c6e1b3fc.PNG)

**Comment by walkor** [comment]
Please install `pcntl` extension.
